version: '3.7'
services:
  postgres:
    image: postgres:14.5-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
